# Generated by Django 4.2 on 2023-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="heart_rate",
            field=models.IntegerField(default=10),
        ),
    ]
