# Generated by Django 4.2 on 2023-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0002_patient_heart_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="heart_rate",
            field=models.IntegerField(default=60),
        ),
    ]
