# Generated by Django 4.2 on 2023-04-05 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0003_alter_patient_heart_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="heart_rate",
            field=models.IntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
